{% set name = "zope.index" %}
{% set version = "5.2.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/zope.index-{{ version }}.tar.gz
  sha256: 055c1949b532b618ee39c6d42f44ee85537a2fe3b1cf333e775a144b0c8b4861

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
  run:
    - btrees >=4.4.1
    - persistent
    - python
    - setuptools
    - six
    - zope.interface

test:
  imports:
    - zope
    - zope.index
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/zopefoundation/zope.index
  summary: Indices for using with catalog like text, field, etc.
  license: ZPL-2.1
  license_file:
    - COPYRIGHT.txt
    - LICENSE.txt

extra:
  recipe-maintainers:
    - osamples
    - izahn
