{% set name = "zope.index" %}
{% set version = "7.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/zope_index-{{ version }}.tar.gz
  sha256: 0dd8ac64dbc1e6f3b51065b98d3c0f2acdb91e0ccdfee17535a56feaf093f6e0

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - pip
    - python
  run:
    - btrees >=4.4.1
    - persistent
    - python
    - setuptools
    - six
    - zope.interface

test:
  imports:
    - zope
    - zope.index
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/zopefoundation/zope.index
  summary: Indices for using with catalog like text, field, etc.
  license: ZPL-2.1
  license_file:
    - COPYRIGHT.txt
    - LICENSE.txt

extra:
  recipe-maintainers:
    - osamples
    - izahn
